# ============================================================
# Backend
# ============================================================

backend = "fastresize"

# ============================================================
# Palette
# ============================================================

color_space = "lab"
palette = "dark"
check_contrast = true

# ============================================================
# Templates
# ============================================================

[templates]

waybar = { template = "waybar.css", target = "/home/benattia/.cache/wallust/waybar.css" }
swaync = { template = "swaync.css", target = "/home/benattia/.cache/wallust/swaync.css" }
hyprland = { template = "hyprland.conf", target = "/home/benattia/.cache/wallust/hyprland.conf" }